# Generated by Django 5.1.5 on 2026-07-27 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Technical & Behavioral Interview', max_length=255)),
                ('scheduled_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('meeting_link', models.URLField(blank=True, help_text='Video call or platform link')),
                ('instructions', models.TextField(blank=True, help_text='Pre-interview preparation guidelines')),
                ('status', models.CharField(choices=[('pending', 'Pending Student Confirmation'), ('accepted', 'Accepted by Student'), ('declined', 'Declined by Student'), ('cancelled', 'Cancelled by Recruiter'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('student_notes', models.TextField(blank=True, help_text='Student decline reason or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='applications.application')),
            ],
            options={
                'verbose_name': 'Interview Schedule',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('app_update', 'Application Status Update'), ('interview_scheduled', 'Interview Scheduled'), ('offer', 'Job Offer'), ('system', 'System Alert')], default='info', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('link', models.CharField(blank=True, help_text='Optional relative frontend URL to open', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
