# Generated by Django 5.1.5 on 2026-07-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Internship Title')),
                ('company_name', models.CharField(default='INPACT Partner', max_length=255)),
                ('location', models.CharField(default='On-site', max_length=255)),
                ('is_remote', models.BooleanField(default=False)),
                ('internship_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], default='full_time', max_length=20)),
                ('stipend', models.CharField(blank=True, help_text='e.g., ₹15,000/month or Unpaid', max_length=100)),
                ('duration_months', models.PositiveSmallIntegerField(default=3, help_text='Duration in months')),
                ('description', models.TextField(help_text='Detailed job description')),
                ('requirements', models.TextField(blank=True, help_text='Eligibility and requirements')),
                ('responsibilities', models.TextField(blank=True, help_text='Key responsibilities')),
                ('skills_required', models.TextField(blank=True, help_text='Comma-separated required skills')),
                ('min_cgpa', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum CGPA required to apply', max_digits=4, null=True)),
                ('departments_allowed', models.TextField(blank=True, help_text='Comma-separated allowed departments (e.g. CSE, ECE, IT). Empty = all allowed.')),
                ('openings', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active / Accepting Applications'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('application_deadline', models.DateTimeField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Internship',
                'verbose_name_plural': 'Internships',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='internships_status_f7773d_idx'), models.Index(fields=['application_deadline'], name='internships_applica_3dd7e1_idx')],
            },
        ),
    ]
