# Generated by Django 5.1.5 on 2026-07-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationcriteria',
            options={'verbose_name_plural': 'Evaluation Criteria'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_number']},
        ),
        migrations.AlterField(
            model_name='question',
            name='keywords',
            field=models.TextField(help_text='Comma-separated keywords for scoring'),
        ),
    ]
