# Generated by Django 5.1.5 on 2026-07-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_evaluationcriteria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcriteria',
            name='shortlist_threshold',
            field=models.PositiveIntegerField(default=50, help_text='Minimum score (0-100) to shortlist'),
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='weight_ats',
            field=models.PositiveIntegerField(default=25, help_text='Weightage % for ATS formatting'),
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='weight_certifications',
            field=models.PositiveIntegerField(default=25, help_text='Weightage % for certifications'),
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='weight_experience',
            field=models.PositiveIntegerField(default=25, help_text='Weightage % for experience'),
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='weight_projects',
            field=models.PositiveIntegerField(default=25, help_text='Weightage % for projects'),
        ),
    ]
