# Generated by Django 5.1.5 on 2026-07-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplyPage', '0004_remove_candidate_resume_link_candidate_resume_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='overall_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume_score',
            field=models.IntegerField(blank=True, help_text='LLM-generated resume score (0-100)', null=True, verbose_name='Resume Score'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='ApplyPage_c_email_7e5396_idx'),
        ),
    ]
