# Generated by Django 5.1.5 on 2026-07-27 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('screening', 'AI Screening In Progress'), ('shortlisted', 'Shortlisted (Passed Screening)'), ('rejected_screening', 'Rejected (Failed Screening)'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('technical_eval', 'In Technical Evaluation'), ('hr_eval', 'In HR Evaluation'), ('offered', 'Offer Extended'), ('accepted', 'Offer Accepted'), ('declined', 'Offer Declined'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=30)),
                ('resume', models.FileField(upload_to='applications/resumes/', verbose_name='Application Resume (PDF)')),
                ('cover_letter', models.TextField(blank=True)),
                ('resume_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI screening score out of 100', max_digits=5, null=True)),
                ('interview_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI interview score out of 100', max_digits=5, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, help_text='Weighted combined score out of 100', max_digits=5, null=True)),
                ('screening_feedback', models.TextField(blank=True, help_text='AI resume feedback')),
                ('interviewer_feedback', models.TextField(blank=True, help_text='AI or human interviewer notes')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin / recruiter notes')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Student Applicant')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internships.internship', verbose_name='Internship Position')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('screening', 'AI Screening In Progress'), ('shortlisted', 'Shortlisted (Passed Screening)'), ('rejected_screening', 'Rejected (Failed Screening)'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('technical_eval', 'In Technical Evaluation'), ('hr_eval', 'In HR Evaluation'), ('offered', 'Offer Extended'), ('accepted', 'Offer Accepted'), ('declined', 'Offer Declined'), ('rejected', 'Rejected')], max_length=30)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('screening', 'AI Screening In Progress'), ('shortlisted', 'Shortlisted (Passed Screening)'), ('rejected_screening', 'Rejected (Failed Screening)'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('technical_eval', 'In Technical Evaluation'), ('hr_eval', 'In HR Evaluation'), ('offered', 'Offer Extended'), ('accepted', 'Offer Accepted'), ('declined', 'Offer Declined'), ('rejected', 'Rejected')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status History Log',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'status'], name='application_applica_b6966f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['internship', 'status'], name='application_interns_b625de_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_1508e0_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['overall_score'], name='application_overall_9afce3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('applicant', 'internship')},
        ),
    ]
